# Generated by Django 4.2.7 on 2023-11-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count_in_stock',
            new_name='countInStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='num_reviews',
            new_name='numReviews',
        ),
    ]
